# Generated by Django 4.1 on 2022-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airplane_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='fuel_capacity',
        ),
        migrations.AddField(
            model_name='airplane',
            name='base_fuel_capacity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='airplane',
            name='passengers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='base_fuel_consumption',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
